language: python
python:
  - "2.7"
before_install:
  - openssl aes-256-cbc -K $encrypted_84a2848b3b48_key -iv $encrypted_84a2848b3b48_iv -in tests/travisci-gcloud_requests.json.enc -out travisci-gcloud_requests.json -d
  - export JSON_CREDENTIALS_FILE=travisci-gcloud_requests.json
  - export DATASTORE_HOST=http://localhost:8080
  - export DATASTORE_DATASET=gcloud
  - mkdir ./datastore
  - curl -o gcd.zip http://storage.googleapis.com/gcd/tools/$GCD_VERSION.zip
  - unzip gcd.zip
  - ./$GCD_VERSION/gcd.sh create -d gcloud ./datastore
  - ./$GCD_VERSION/gcd.sh start --port=8080 ./datastore &
install: "pip install -r requirements.txt"
script: "env PYTHONPATH=. python tests/test_datastore.py"
addons:
  code_climate:
    repo_token: 1ae0e51788ad23c845e353566a8b245c4c2929035709105e2b8407d6ae2e2b51
