language: python
python:
  - "2.7"
before_install:
  - export DATASTORE_HOST=http://localhost:8080
  - export DATASTORE_DATASET=gcloud
  - mkdir ./datastore
  - curl -o gcd.zip http://storage.googleapis.com/gcd/tools/$GCD_VERSION.zip
  - unzip gcd.zip
  - ./$GCD_VERSION/gcd.sh create -d gcloud ./datastore
  - ./$GCD_VERSION/gcd.sh start --testing --port=8080 ./datastore &
install: "pip install -r requirements.txt"
script: py.test