language: python
python:
  - "2.7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libtool
  - openssl aes-256-cbc -K $encrypted_84a2848b3b48_key -iv $encrypted_84a2848b3b48_iv -in tests/leadpages-8687295e9cc6.json.enc -out leadpages-8687295e9cc6.json -d
  - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-141.0.0-linux-x86_64.tar.gz -O /tmp/gcloud.tar.gz
  - tar -xvf /tmp/gcloud.tar.gz -C $HOME
  - export PATH=$HOME/google-cloud-sdk/bin:$PATH
  - export GOOGLE_APPLICATION_CREDENTIALS="leadpages-8687295e9cc6.json"
  - gcloud -q components install beta gcd-emulator
  - mkdir ./datastore
  - gcloud -q beta emulators datastore start --data-dir=./datastore --consistency 1.0 --host-port localhost:8080 --project=gcloud --legacy &
install: "pip install -U -r requirements-dev.txt"
script: "env PYTHONPATH=. DATASTORE_HOST='http://localhost:8080' DATASTORE_DATASET=gcloud python tests/test_datastore.py"
addons:
  code_climate:
    repo_token: 1ae0e51788ad23c845e353566a8b245c4c2929035709105e2b8407d6ae2e2b51
